version: "3"
services:
  app:
    container_name: projectManagementFrontend
    image: bxdman/ceprojectmanagement
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NEXT_PUBLIC_URL
      - NEXTAUTH_URL
      - NEXT_PUBLIC_ENDPOINT
      - NEXTAUTH_SECRET
      - MINIO_ENDPOINT
    restart: always
    network_mode: host