version: "3"
services:
  app:
    container_name: projectManagementFrontend
    image: bxdman/ceprojectmanagement
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NEXTAUTH_URL
      - NEXT_PUBLIC_ENDPOINT
      - NEXTAUTH_SECRET
      - MINIO_ENDPOINT
    restart: always
    ports:
      - "3000:3000"